# Venmo `3 points`

Venmo is used for two things:

1. Sending money to people
2. Spying on people sending money to people

For some reason, they have (...had) a public API. You can find it here: https://venmo.com/api/v5/public

**Topics covered:**

* APIs

## Using the Venmo API  `3 points`

### Make a _successful_ request to the Venmo API

You'll need to pretend to be a browser.

In [8]:
import requests
import pandas as pd
import json
link = 'https://venmo.com/api/v5/public'

In [3]:
response = requests.get(link, headers={'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36'})

In [4]:
data = json.loads(response.content.decode('utf-8'))['data']

### How many results do you get by default?

In [5]:
# 13 entries
len(data)

13

### Print out each transaction's username and message

In [6]:
# just do for "item in data:" and then get item['actor']['username']
for item in range(0,len(data)):
    username = data[item]['actor']['username']
    message = data[item]['message']
    print(username,' : ',message)

Marc-K  :  Miss you
Amanda-K  :  Groceries
Skye-F  :  Virtual coffee date!!!
Julia-S  :  To help w/ your bills this month
Betty A  :  Thanks for everything you do
Joe-R  :  Rent's due, dude
Derek-B  :  Takeout > Going out
Courtney-S  :  Thank you, friend
Peyton-L  :  Pizza for din. And bfast too.
Kay-N  :  You got this
Kerrie-N  :  Dinner
Erin-G  :  Treat yo self
Shelby-K  :  Grab a snack on me!

### Being lazy and effective `1 point`

Convert the list of transactions into a dataframe.

In [21]:
pd.json_normalize(data, record_path=['transactions'])

,target.username,target.picture,target.is_business,target.name,target.firstname,target.lastname,target.cancelled,target.date_created,target.external_id,target.id
0,Erica-M,,False,Erica M,Erica,M,False,2020-02-02T16:57:40,2141499719669514525,2141499719669514525
1,Jordan-K,,False,Jordan K,Jordan,K,False,2020-02-02T16:57:40,2141499719669514525,2141499719669514525
2,John-G,,False,John G,John,G,False,2020-02-02T16:57:40,2141499719669514525,2141499719669514525
3,Pluto-S,,False,Pluto S,Pluto,S,False,2020-02-02T16:57:40,2141499719669514525,2141499719669514525
4,Liz-A,,False,Liz A,Liz,A,False,2020-02-02T16:57:40,2141499719669514525,2141499719669514525
5,Aaron-D,,False,Aaron D,Aaron,D,False,2020-02-02T16:57:40,2141499719669514525,2141499719669514525
6,Kaylee-N,,False,Kaylee N,Kaylee,N,False,2020-02-02T16:57:40,2141499719669514525,2141499719669514525
7,Woot-H,,False,Woot H,Woot,H,False,2020-02-02T16:57:40,2141499719669514525,2141499719669514525
8,Sean-N,,False,Sean N,Sean,N,False,2020-02-02T16:57:40,2141499719669514525,2141499719669514525
9,Annalee-L,,False,Annalee L,Annalee,L,False,2020-02-02T16:57:40,2141499719669514525,2141499719669514525
10,Benny-N,,False,Benny N,Benny,N,False,2020-02-02T16:57:40,2141499719669514525,2141499719669514525
11,Liz-A,,False,Liz A,Liz,A,False,2020-02-02T16:57:40,2141499719669514525,2141499719669514525
12,Ashley-P,,False,Ashley P,Ashley,P,False,2020-02-02T16:57:405,2141499719669514525,2141499719669514525

## But now: to reality

You should cry a little bit, because **this data isn't real**. It *used* to be real, but it isn't any more, because Venmo finally decided it was a bit too much of an invasion of privacy.